
services:
  db:
    image: postgres:10
    container_name: pioneer
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_pioneer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pioneer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pioneer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: pioneer_app
#    restart: unless-stopped
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pioneer
#      SPRING_DATASOURCE_USERNAME: postgres_pioneer
#      SPRING_DATASOURCE_PASSWORD: 123456
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

volumes:
  db_data:
  redis_data: