version: '3.8'

services:
  db:
    image: postgres:10
    container_name: pioneer
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_pioneer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pioneer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: